const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const PoiSchema = new Schema({
    name: { type: String, required: true },
    type: {
        type: String,
        enum: ['npc', 'object', 'entrance', 'landmark', 'danger', 'quest', 'shop', 'other'],
        default: 'other'
    },
    description: String,
    disposition: String,
    icon: String,
    persistent: { type: Boolean, default: true },
    discovered: { type: Boolean, default: false },
    interactionCount: { type: Number, default: 0 },
    lastInteraction: String,
    metadata: Schema.Types.Mixed,

    // Location reference
    settlement: { type: Schema.Types.ObjectId, ref: 'Settlement', required: true },
    locationId: { type: Schema.Types.ObjectId, required: true },
    locationName: { type: String, required: true },

    // Tracking
    autoGenerated: { type: Boolean, default: false }
}, { timestamps: true });

// Compound indexes for common queries
PoiSchema.index({ settlement: 1, locationId: 1 });
PoiSchema.index({ settlement: 1, type: 1, name: 1 });
PoiSchema.index({ settlement: 1, name: 1 });

module.exports = mongoose.model('Poi', PoiSchema);
